### PR TITLE
Send pid as group leader

### PR DESCRIPTION
**Pull request by fishcakez**

### CODE REVIEW

**Comment by fishcakez** [comment]
Please could you release a new version once this and #16 are merged.

**Comment by MSch** [comment]
@fishcakez Thanks for your PRs and sorry for taking so long to get back to you.

We introduced CLAs for all our open-source projects, so could you please sign one of the CLAs here: https://pspdfkit.com/guides/web/current/miscellaneous/contributing/

Then I'll merge and release. Thank you!

**Comment by alco** [comment]
@MSch Ping. I believe @fishcakez has signed the CLA. This should be good to merge.

**Comment by AndrewDryga** [comment]
Yes @MSch, come on. :)

**Comment by MSch** [comment]
Done - 1.0.5 is published. Sorry for taking so long 🙈

**Pull request merged**
