### PR TITLE
Obey lager level and Logger compile time level

### PR DESCRIPTION
**Pull request by fishcakez**
Allow the lager level to be set like a normal lager handler but limit the level to be greater than or equal to Logger's `:compile_time_purge_level` (set at compile time).
- [x] Discussion
- [x] Tests
- [x] Resolve conflicts

### CODE REVIEW

**Comment by fishcakez** [comment]
I don't think it make sense to always set the lager level to `:debug` because this means all lager messages will be formatted even if they are going to be ignored. Instead it would be better to default to the lager level `:debug` but allow it to be overridden by setting the lager level via config (like other lager handlers):

``` elixir
use Mix.Config
config :lager, :handlers, [{LagerLogger, [level: :debug]}]
```

For convenience it might also be nice to obey Logger's `:compile_time_purge_level`. However this might be awkward to test nor worth the potential confusion when the lager level can be set in the compulsory configuration entry.

**Comment by MSch** [comment]
Sounds good to me :+1:

**Comment by fishcakez** [comment]
I've added a `flush/0` function that works similar to `Logger.flush()` and a few integration tests. Also I removed the `:compile_time_purge_level` feature.

Note that the lager level configuration can likely be used instead of your filter for the exometer reporter.

**Comment by MSch** [comment]
> Note that the lager level configuration can likely be used instead of your filter for the exometer reporter.

@fishcakez how? I could change the log level for lager, but AFAK there's no way to do "reverse tracing" in lager, e.g. go with debug for all messages except ones from exometer.

Also, do you have anything else planned for this PR or can it be merged?

**Comment by fishcakez** [comment]
> @fishcakez how? I could change the log level for lager, but AFAK there's no way to do "reverse tracing" in lager, e.g. go with debug for all messages except ones from exometer.

Ah, I was thinking it likely that only exometer would be using lager and the rest Logger or error_logger. I think filtering like that should be done in Logger, not here, because the same issue might occur there.

> Also, do you have anything else planned for this PR or can it be merged?

Feel free to merge.

**Pull request merged**
